# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [3]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [11]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
a = np.arange(2,9)
print(a)
print(type(a))

[2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


### Step 3. Reshape 1D to 2D Array

In [29]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Step 4. Create a Linspace array

In [37]:
np.linspace(0,5,30)
# --( upper - lower )/(n-1)

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

### Step 5. Create a Random Numbered Array

In [39]:
np.random.rand(2)

array([0.5102603 , 0.95892688])

In [41]:
np.random.rand(2,5)

array([[0.08005728, 0.11549894, 0.64135637, 0.10186106, 0.88812613],
       [0.09464469, 0.44389877, 0.17321407, 0.01050809, 0.32394918]])

### Step 6. Create a Random Integer Array

In [55]:
np.random.randint(1,100,size=10)



array([15, 11,  9, 33, 29, 59, 35, 62, 45, 69])

In [57]:
np.random.randint(1,100,size=(2,4))
# df shape -> (row,column)

array([[99, 51, 82, 11],
       [43, 98, 85, 45]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [59]:
arr = np.random.randint(1,100,size=10)
arr 

array([31,  8, 62, 86, 83, 75, 20, 84, 74, 67])

In [61]:
arr.max()

86

In [63]:
arr.min()

8

In [67]:
arr.argmax()

3

In [69]:
arr.argmin()

1

### Step 8. Indexing in 1D Array

In [75]:
arr[1]

8

In [77]:
arr[1:8]

array([ 8, 62, 86, 83, 75, 20, 84])

### Step 9. Indexing in 2D Array

In [112]:
arr2d = np.random.rand(4,5)
print(arr2d)
print("============================ B & D =")
print(arr2d[1::2,::])
print("============================= A & C ")
print(arr2d[0::2,0::2])
print("============================= Box ")
print(arr2d[1:3:,1:4:])

[[0.26426353 0.76572678 0.25202399 0.71477899 0.22909013]
 [0.96810309 0.78104449 0.65433899 0.77123796 0.84778819]
 [0.7294389  0.67456537 0.82423864 0.42395797 0.45833598]
 [0.51491106 0.15607468 0.44062051 0.85237528 0.20037507]]
============================ B & D =
[[0.96810309 0.78104449 0.65433899 0.77123796 0.84778819]
 [0.51491106 0.15607468 0.44062051 0.85237528 0.20037507]]
============================= A & C 
[[0.26426353 0.25202399 0.22909013]
 [0.7294389  0.82423864 0.45833598]]
============================= Box 
[[0.78104449 0.65433899 0.77123796]
 [0.67456537 0.82423864 0.42395797]]


### Step 10. Conditional Selection

In [119]:
arr[arr>4]

array([31,  8, 62, 86, 83, 75, 20, 84, 74, 67])

In [110]:
arr2d[arr2d<0.5]

array([0.41977316, 0.33361368, 0.46696173, 0.34843268, 0.36361758,
       0.48082405, 0.18394364, 0.05758218, 0.14822168])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [121]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

In [125]:
users =  pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',sep='|')
users

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 3. Assign it to a variable called users and use the 'user_id' as index

### Step 4. See the first 25 entries

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

943

### Step 7. What is the number of columns in the dataset?

4

### Step 8. Print the name of all the columns.

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

21

### Step 13. What is the most frequent occupation?

occupation
student    196
Name: count, dtype: int64

### Step 14. Summarize the DataFrame.

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

34.05196182396607

### Step 18. What is the age with least occurrence?

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

### You're not just learning, you're mastering it. Keep aiming higher! 🚀