<h2 align="center">pandas</h2>

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2


In [3]:
A=pd.Series([2,3,4,5],index=['a','b','c','d'])#you can specify index

In [4]:
A

a    2
b    3
c    4
d    5
dtype: int64

In [5]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [6]:
type(A.values)

numpy.ndarray

In [7]:
type(A)

pandas.core.series.Series

In [8]:
#we can also change get access of values as arrays or lists for ex:-
A['a']

2

In [9]:
A['a':'c']#final index is also included

a    2
b    3
c    4
dtype: int64

In [10]:
#convert dictonay into set
grades_dict={'a':4,'b':3.5,'c':3,'d':2.5}
grades=pd.Series(grades_dict)

In [11]:
print(grades.values)

[4.  3.5 3.  2.5]


In [12]:
print(grades.keys)

<bound method Series.keys of a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64>


In [13]:
grades

a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64

In [14]:
#to acccess
grades['a']

4.0

In [15]:
#can also be accessed by index for ex:-
grades[0:2]

a    4.0
b    3.5
dtype: float64

In [16]:
marks_dict={'a':85,'b':75,'c':65,'d':55,'e':45}
marks=pd.Series(marks_dict)

In [17]:
marks

a    85
b    75
c    65
d    55
e    45
dtype: int64

In [18]:
grades

a    4.0
b    3.5
c    3.0
d    2.5
dtype: float64

In [19]:
D=pd.DataFrame({'Marks':marks,'Grades':grades})

In [20]:
D

Marks  Grades
a     85     4.0
b     75     3.5
c     65     3.0
d     55     2.5
e     45     NaN

In [21]:
#for transpose version
D.T

a     b     c     d     e
Marks   85.0  75.0  65.0  55.0  45.0
Grades   4.0   3.5   3.0   2.5   NaN

In [22]:
#for access values of D
D.values
#returns two dimentional array

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5],
       [45. ,  nan]])

In [23]:
D.values[2,0]

65.0

In [24]:
D.values[2,:]

array([65.,  3.])

In [25]:
D.values[3,1]

2.5

In [26]:
#returns all colums
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [27]:
D.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [28]:
#to add new column
D['ScaledMarks']=100*(D['Marks']/90)#out od 90
D['new']=1

In [29]:
D

Marks  Grades  ScaledMarks  new
a     85     4.0    94.444444    1
b     75     3.5    83.333333    1
c     65     3.0    72.222222    1
d     55     2.5    61.111111    1
e     45     NaN    50.000000    1

In [30]:
#to delete a column
del D['new']

In [31]:
D

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

##### masking

In [32]:
#for Ex:-
g=D[D['Marks']>70]

In [33]:
g

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333

In [34]:
#NAN ex:-
print(pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}]))

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0


In [35]:
D

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [36]:
#to handle NAN you can use this fun which set fix value
D.fillna(0)

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     0.0    50.000000

In [37]:
D

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [38]:
#or you can drop that data

In [39]:
D.dropna()

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111

#### indexes

In [40]:
data=pd.Series(['a','b','c'],index=[1,3,5]) #provide explicit index

In [41]:
data[1] #explicit index
#use loc insted

'a'

In [42]:
#at index 1 will be printed
data[1:3] #implicit index 
#use iloc insted

3    b
5    c
dtype: object

In [43]:
data.loc[1:3] #will use explicit index which you provided

1    a
3    b
dtype: object

In [44]:
data.loc[1:]

1    a
3    b
5    c
dtype: object

In [45]:
data.iloc[1:3] #will use implicit index

3    b
5    c
dtype: object

In [46]:
D

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [47]:
D.iloc[2,:] #row at second index is c row

Marks          65.000000
Grades          3.000000
ScaledMarks    72.222222
Name: c, dtype: float64

In [48]:
D

Marks  Grades  ScaledMarks
a     85     4.0    94.444444
b     75     3.5    83.333333
c     65     3.0    72.222222
d     55     2.5    61.111111
e     45     NaN    50.000000

In [49]:
D.iloc[1:3,0:2] # Slice rows 1 to 3 and columns A and B using iloc
#D.iloc[::-1,::-1] also can be reverced by this 

Marks  Grades
b     75     3.5
c     65     3.0

### intro to manipulate csv file data

In [50]:
import numpy as np
from sklearn.impute import SimpleImputer #to deal with empty data

In [77]:
df=pd.read_csv("E:\\DS\\project\\covid\\2019_nCoV_data.csv")

In [78]:
df.head() #gives top records you specify in the parameter,by default it's 5

Sno             Date Province/State Country      Last Update  Confirmed  \
0    1  1/22/2020 12:00          Anhui   China  1/22/2020 12:00          1   
1    2  1/22/2020 12:00        Beijing   China  1/22/2020 12:00         14   
2    3  1/22/2020 12:00      Chongqing   China  1/22/2020 12:00          6   
3    4  1/22/2020 12:00         Fujian   China  1/22/2020 12:00          1   
4    5  1/22/2020 12:00          Gansu   China  1/22/2020 12:00          0   

   Deaths  Recovered  
0       0          0  
1       0          0  
2       0          0  
3       0          0  
4       0          0

In [79]:
print(df.columns)

Index(['Sno', 'Date', 'Province/State', 'Country', 'Last Update', 'Confirmed',
       'Deaths', 'Recovered'],
      dtype='object')


In [80]:
#don't run again after execute first time.it will give error
#because there won't be any colums you specified
df.drop(['Sno','Last Update'],axis=1,inplace=True)

if you don't write inplace=true then it will return on temporary varible
df will unchanged

In [81]:
print(df.columns)

Index(['Date', 'Province/State', 'Country', 'Confirmed', 'Deaths',
       'Recovered'],
      dtype='object')


In [82]:
df.head()

Date Province/State Country  Confirmed  Deaths  Recovered
0  1/22/2020 12:00          Anhui   China          1       0          0
1  1/22/2020 12:00        Beijing   China         14       0          0
2  1/22/2020 12:00      Chongqing   China          6       0          0
3  1/22/2020 12:00         Fujian   China          1       0          0
4  1/22/2020 12:00          Gansu   China          0       0          0

In [83]:
#to rename columns
df.rename(columns={'Province/State':'Provance'})

Date   Provance             Country  Confirmed  Deaths  \
0      1/22/2020 12:00      Anhui               China          1       0   
1      1/22/2020 12:00    Beijing               China         14       0   
2      1/22/2020 12:00  Chongqing               China          6       0   
3      1/22/2020 12:00     Fujian               China          1       0   
4      1/22/2020 12:00      Gansu               China          0       0   
...                ...        ...                 ...        ...     ...   
24704  3/26/2020 22:00        NaN           Venezuela        107       0   
24705  3/26/2020 22:00        NaN             Vietnam        153       0   
24706  3/26/2020 22:00        NaN  West Bank and Gaza         84       1   
24707  3/26/2020 22:00        NaN              Zambia         16       0   
24708  3/26/2020 22:00        NaN            Zimbabwe          3       1   

       Recovered  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
24704         15  
24705         20  
24706         17  
24707          0  
24708          0  

[24709 rows x 6 columns]

it returned in temporary to store it use inplace=True

In [84]:
df.head()

Date Province/State Country  Confirmed  Deaths  Recovered
0  1/22/2020 12:00          Anhui   China          1       0          0
1  1/22/2020 12:00        Beijing   China         14       0          0
2  1/22/2020 12:00      Chongqing   China          6       0          0
3  1/22/2020 12:00         Fujian   China          1       0          0
4  1/22/2020 12:00          Gansu   China          0       0          0

In [85]:
df.rename(columns={'Province/State':'Provance'},inplace=True)

In [86]:
df.head()

Date   Provance Country  Confirmed  Deaths  Recovered
0  1/22/2020 12:00      Anhui   China          1       0          0
1  1/22/2020 12:00    Beijing   China         14       0          0
2  1/22/2020 12:00  Chongqing   China          6       0          0
3  1/22/2020 12:00     Fujian   China          1       0          0
4  1/22/2020 12:00      Gansu   China          0       0          0

In [87]:
#to convert date to pandas formate
df['Date'] = pd.to_datetime(df['Date'],errors='coerce')

# Create new columns for date and time
df['Only_Date'] = df['Date'].dt.date


errors='coerce' will convert invalid/malformed entries to NaT (Not a Time), so they won't break the code.

In [88]:
df

Date   Provance             Country  Confirmed  Deaths  \
0     2020-01-22 12:00:00      Anhui               China          1       0   
1     2020-01-22 12:00:00    Beijing               China         14       0   
2     2020-01-22 12:00:00  Chongqing               China          6       0   
3     2020-01-22 12:00:00     Fujian               China          1       0   
4     2020-01-22 12:00:00      Gansu               China          0       0   
...                   ...        ...                 ...        ...     ...   
24704 2020-03-26 22:00:00        NaN           Venezuela        107       0   
24705 2020-03-26 22:00:00        NaN             Vietnam        153       0   
24706 2020-03-26 22:00:00        NaN  West Bank and Gaza         84       1   
24707 2020-03-26 22:00:00        NaN              Zambia         16       0   
24708 2020-03-26 22:00:00        NaN            Zimbabwe          3       1   

       Recovered   Only_Date  
0              0  2020-01-22  
1              0  2020-01-22  
2              0  2020-01-22  
3              0  2020-01-22  
4              0  2020-01-22  
...          ...         ...  
24704         15  2020-03-26  
24705         20  2020-03-26  
24706         17  2020-03-26  
24707          0  2020-03-26  
24708          0  2020-03-26  

[24709 rows x 7 columns]

In [89]:
del df['Date']

In [90]:
df.head()

Provance Country  Confirmed  Deaths  Recovered   Only_Date
0      Anhui   China          1       0          0  2020-01-22
1    Beijing   China         14       0          0  2020-01-22
2  Chongqing   China          6       0          0  2020-01-22
3     Fujian   China          1       0          0  2020-01-22
4      Gansu   China          0       0          0  2020-01-22

In [91]:
#to specify the order of column
df=df[['Only_Date','Provance','Country','Confirmed','Deaths','Recovered']]

In [92]:
df.head()

Only_Date   Provance Country  Confirmed  Deaths  Recovered
0  2020-01-22      Anhui   China          1       0          0
1  2020-01-22    Beijing   China         14       0          0
2  2020-01-22  Chongqing   China          6       0          0
3  2020-01-22     Fujian   China          1       0          0
4  2020-01-22      Gansu   China          0       0          0

In [93]:
df.rename(columns={'Only_Date':'Date'},inplace=True)

In [94]:
df.head()

Date   Provance Country  Confirmed  Deaths  Recovered
0  2020-01-22      Anhui   China          1       0          0
1  2020-01-22    Beijing   China         14       0          0
2  2020-01-22  Chongqing   China          6       0          0
3  2020-01-22     Fujian   China          1       0          0
4  2020-01-22      Gansu   China          0       0          0

In [95]:
#to describe most of the statistics of the data
df.describe()

Confirmed        Deaths     Recovered
count  24709.000000  24709.000000  24709.000000
mean     284.015662     10.641507     94.259541
std     3247.033278    172.711165   1728.675580
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        1.000000      0.000000      0.000000
75%       15.000000      0.000000      0.000000
max    80589.000000   8215.000000  61201.000000

In [96]:
a=df.describe()

In [97]:
type(a)

pandas.core.frame.DataFrame

In [98]:
b=df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24709 entries, 0 to 24708
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Date       21528 non-null  object
 1   Provance   20627 non-null  object
 2   Country    24709 non-null  object
 3   Confirmed  24709 non-null  int64 
 4   Deaths     24709 non-null  int64 
 5   Recovered  24709 non-null  int64 
dtypes: int64(3), object(3)
memory usage: 1.1+ MB


In [99]:
#there are null values at some feild
#to deal with it there are two ways 1 using simple imputer
#and 3 fillna
df=df.fillna('NA')

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24709 entries, 0 to 24708
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Date       24709 non-null  object
 1   Provance   24709 non-null  object
 2   Country    24709 non-null  object
 3   Confirmed  24709 non-null  int64 
 4   Deaths     24709 non-null  int64 
 5   Recovered  24709 non-null  int64 
dtypes: int64(3), object(3)
memory usage: 1.1+ MB


In [101]:
df.head()

Date   Provance Country  Confirmed  Deaths  Recovered
0  2020-01-22      Anhui   China          1       0          0
1  2020-01-22    Beijing   China         14       0          0
2  2020-01-22  Chongqing   China          6       0          0
3  2020-01-22     Fujian   China          1       0          0
4  2020-01-22      Gansu   China          0       0          0

### groupby command

In [105]:
df2 = df.groupby('Country')[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()

ValueError: cannot insert Country, already exists

In [104]:
df2

Country  Confirmed  Deaths  Recovered
0                        Azerbaijan          1       0          0
1                  03-06-2020 22:00       1018       4        955
2                       Afghanistan        541       9         13
3                           Albania       1171      37         50
4                           Algeria       2154     159        420
..                              ...        ...     ...        ...
221                         Vietnam       1960       0        623
222              West Bank and Gaza         84       1         17
223                          Zambia         45       0          0
224                        Zimbabwe         19       4          0
225  occupied Palestinian territory         25       0          0

[226 rows x 4 columns]

In [107]:
df2 = df.groupby(['Country','Date'])[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()


In [110]:
df2

Country        Date  Confirmed  Deaths  Recovered
0                         Azerbaijan  2020-02-28          1       0          0
1                   03-06-2020 22:00          NA       1018       4        955
2                        Afghanistan  2020-02-24          1       0          0
3                        Afghanistan  2020-02-25          1       0          0
4                        Afghanistan  2020-02-26          1       0          0
...                              ...         ...        ...     ...        ...
3217  occupied Palestinian territory  2020-03-14          0       0          0
3218  occupied Palestinian territory  2020-03-15          0       0          0
3219  occupied Palestinian territory  2020-03-16          0       0          0
3220  occupied Palestinian territory  2020-03-17          0       0          0
3221  occupied Palestinian territory          NA         25       0          0

[3222 rows x 5 columns]

In [113]:
df3=df2[df2['Confirmed']>100]

In [114]:
df3

Country        Date  Confirmed  Deaths  Recovered
1     03-06-2020 22:00          NA       1018       4        955
33             Albania  2020-03-23        104       4          2
34             Albania  2020-03-24        123       5         10
35             Albania  2020-03-25        146       5         17
36             Albania  2020-03-26        174       6         17
...                ...         ...        ...     ...        ...
3195           Vietnam  2020-03-23        123       0         17
3196           Vietnam  2020-03-24        134       0         17
3197           Vietnam  2020-03-25        141       0         17
3198           Vietnam  2020-03-26        153       0         20
3199           Vietnam          NA        378       0        198

[1045 rows x 5 columns]