In [5]:
import numpy as np

def generate_binary_tree_adjacency_matrix(n):
    # Initialize N x N adjacency matrix with zeros
    adj_matrix = np.zeros((n, n), dtype=int)
    
    # Populate edges for a complete binary tree
    for i in range(1, n + 1):
        # Left child: 2*i
        if 2 * i <= n:
            adj_matrix[i-1, 2*i-1] = 1
            adj_matrix[2*i-1, i-1] = 1  # Undirected edge
        # Right child: 2*i + 1
        if 2 * i + 1 <= n:
            adj_matrix[i-1, 2*i] = 1
            adj_matrix[2*i, i-1] = 1  # Undirected edge
            
    return adj_matrix

def compute_eigen_properties(adj_matrix):
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(adj_matrix)
    
    # Convert negative eigenvalues to positive
    positive_eigenvalues = np.abs(eigenvalues)
    
    # Sum of eigenvalues
    eigen_sum = np.sum(positive_eigenvalues)
    
    # Eigenvalue matrix (diagonal)
    eigen_matrix = np.diag(positive_eigenvalues)
    
    return positive_eigenvalues, eigen_sum, eigen_matrix, eigenvectors

def main():
    # Get user input
    try:
        n = int(input("Enter the number of nodes (e.g., 50): "))
        if n < 1:
            print("Please enter a positive integer.")
            return
    except ValueError:
        print("Invalid input. Please enter a positive integer.")
        return
    
    # Generate adjacency matrix
    adj_matrix = generate_binary_tree_adjacency_matrix(n)
    
    # Compute eigenvalue properties
    eigenvalues, eigen_sum, eigen_matrix, eigenvectors = compute_eigen_properties(adj_matrix)
    
    # Print results
    print("\nAdjacency Matrix:")
    print(adj_matrix)
    
    print("\nEigenvalues (positive):")
    print(eigenvalues)
    
    print("\nSum of Eigenvalues:")
    print(eigen_sum)
    
    print("\nEigenvalue Matrix (Diagonal):")
    print(eigen_matrix)
    
    print("\nEigenvector Matrix:")
    print(eigenvectors)

# ✅ This is the correct condition
if __name__ == "__main__":
    main()


Enter the number of nodes (e.g., 50):  3



Adjacency Matrix:
[[0 1 1]
 [1 0 0]
 [1 0 0]]

Eigenvalues (positive):
[1.41421356 0.         1.41421356]

Sum of Eigenvalues:
2.8284271247461903

Eigenvalue Matrix (Diagonal):
[[1.41421356 0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         1.41421356]]

Eigenvector Matrix:
[[-0.70710678  0.         -0.70710678]
 [ 0.5        -0.70710678 -0.5       ]
 [ 0.5         0.70710678 -0.5       ]]


In [9]:
import numpy as np

def generate_binary_tree_adjacency_matrix(n):
    # Initialize N x N adjacency matrix with zeros
    adj_matrix = np.zeros((n, n), dtype=int)
    
    # Populate edges for a complete binary tree
    for i in range(1, n + 1):
        # Left child: 2*i
        if 2 * i <= n:
            adj_matrix[i - 1, 2 * i - 1] = 1
            adj_matrix[2 * i - 1, i - 1] = 1  # Undirected edge
        # Right child: 2*i + 1
        if 2 * i + 1 <= n:
            adj_matrix[i - 1, 2 * i] = 1
            adj_matrix[2 * i, i - 1] = 1  # Undirected edge
            
    return adj_matrix

def compute_eigen_properties(adj_matrix):
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(adj_matrix)
    
    # Sum of absolute eigenvalues
    eigen_sum = np.sum(np.abs(eigenvalues))
    
    # Eigenvalue matrix (keep negative signs)
    eigen_matrix = np.diag(eigenvalues)
    
    return eigenvalues, eigen_sum, eigen_matrix, eigenvectors

def main():
    # Get user input
    try:
        n = int(input("Enter the number of nodes (e.g., 50): "))
        if n < 1:
            print("Please enter a positive integer.")
            return
    except ValueError:
        print("Invalid input. Please enter a positive integer.")
        return
    
    # Generate adjacency matrix
    adj_matrix = generate_binary_tree_adjacency_matrix(n)
    
    # Compute eigenvalue properties
    eigenvalues, eigen_sum, eigen_matrix, eigenvectors = compute_eigen_properties(adj_matrix)
    
    # Print results
    print("\nAdjacency Matrix:")
    print(adj_matrix)
    
    print("\nEigenvalues (original):")
    print(eigenvalues)
    
    print("\nSum of Absolute Eigenvalues:")
    print(eigen_sum)
    
    print("\nEigenvalue Matrix (Diagonal):")
    print(eigen_matrix)
    
    print("\nEigenvector Matrix:")
    print(eigenvectors)

# ✅ Correct entry point
if __name__ == "__main__":
    main()


Enter the number of nodes (e.g., 50):  5



Adjacency Matrix:
[[0 1 1 0 0]
 [1 0 0 1 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]

Eigenvalues (original):
[-1.84775907e+00 -7.65366865e-01  7.57594969e-34  7.65366865e-01
  1.84775907e+00]

Sum of Absolute Eigenvalues:
5.226251859505507

Eigenvalue Matrix (Diagonal):
[[-1.84775907e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00 -7.65366865e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.57594969e-34  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  7.65366865e-01
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.84775907e+00]]

Eigenvector Matrix:
[[ 5.00000000e-01  5.00000000e-01  2.21968265e-32 -5.00000000e-01
  -5.00000000e-01]
 [-6.53281482e-01  2.70598050e-01  7.85046229e-17  2.70598050e-01
  -6.53281482e-01]
 [-2.70598050e-01 -6.53281482e-01 -7.85046229e-17 -6.53281482e-01
  -2.70598050e-01]
 [ 3.53553391e-01 -3.53553

In [15]:
import numpy as np

np.set_printoptions(precision=8, suppress=True)  # ✅ Format output nicely

def generate_binary_tree_adjacency_matrix(n):
    adj_matrix = np.zeros((n, n), dtype=int)
    for i in range(1, n + 1):
        if 2 * i <= n:
            adj_matrix[i - 1, 2 * i - 1] = 1
            adj_matrix[2 * i - 1, i - 1] = 1
        if 2 * i + 1 <= n:
            adj_matrix[i - 1, 2 * i] = 1
            adj_matrix[2 * i, i - 1] = 1
    return adj_matrix

def compute_eigen_properties(adj_matrix):
    eigenvalues, eigenvectors = np.linalg.eigh(adj_matrix)
    eigen_sum = np.sum(np.abs(eigenvalues))
    eigen_matrix = np.diag(eigenvalues)
    return eigenvalues, eigen_sum, eigen_matrix, eigenvectors

def main():
    try:
        n = int(input("Enter the number of nodes (e.g., 5): "))
        if n < 1:
            print("Please enter a positive integer.")
            return
    except ValueError:
        print("Invalid input. Please enter a positive integer.")
        return

    adj_matrix = generate_binary_tree_adjacency_matrix(n)
    eigenvalues, eigen_sum, eigen_matrix, eigenvectors = compute_eigen_properties(adj_matrix)

    print("\nAdjacency Matrix:")
    print(adj_matrix)

    print("\nEigenvalues (original):")
    print(eigenvalues)

    print("\nSum of Absolute Eigenvalues:")
    print(eigen_sum)

    print("\nEigenvalue Matrix (Diagonal):")
    print(eigen_matrix)

    print("\nEigenvector Matrix (columns):")
    print(eigenvectors)

# ✅ Entry point
if __name__ == "__main__":
    main()


Enter the number of nodes (e.g., 5):  50



Adjacency Matrix:
[[0 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Eigenvalues (original):
[-2.52536296 -2.37581023 -2.28824561 -2.08382212 -2.         -2.
 -1.7259281  -1.62416418 -1.41421356 -1.41421356 -1.41421356 -1.41421356
 -1.41421356 -1.20214063 -1.13031146 -0.87403205 -0.48645782 -0.24418983
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.          0.          0.          0.          0.          0.
  0.          0.          0.24418983  0.48645782  0.87403205  1.13031146
  1.20214063  1.41421356  1.41421356  1.41421356  1.41421356  1.41421356
  1.62416418  1.7259281   2.          2.          2.08382212  2.28824561
  2.37581023  2.52536296]

Sum of Absolute Eigenvalues:
55.26306558848532

Eigenvalue Matrix (Diagonal):
[[-2.52536296  0.          0.         ...  0.          0.
   0.        ]
 [ 0.         -2.37581023  0.         ...  0.          0.
   0.        ]
 [ 0.          0.        

In [20]:
"""
Binary Tree Spectral Analysis Tool

This program:
1. Generates the adjacency matrix for a complete binary tree with `n` nodes.
2. Computes the eigenvalues and eigenvectors of the adjacency matrix.
3. Outputs the:
   - Adjacency matrix
   - Eigenvalues (with both positive and negative values)
   - Sum of absolute eigenvalues
   - Diagonal eigenvalue matrix
   - Eigenvector matrix

Useful for understanding graph structure using spectral (eigen) analysis.

Author: Your Name
"""

import numpy as np

# ✅ Ensure full matrix printing without truncation
np.set_printoptions(threshold=np.inf, linewidth=np.inf, precision=8, suppress=True)

def generate_binary_tree_adjacency_matrix(n):
    # Initialize N x N adjacency matrix with zeros
    adj_matrix = np.zeros((n, n), dtype=int)

    # Populate edges for a complete binary tree
    for i in range(1, n + 1):
        if 2 * i <= n:
            adj_matrix[i - 1, 2 * i - 1] = 1
            adj_matrix[2 * i - 1, i - 1] = 1  # Undirected edge
        if 2 * i + 1 <= n:
            adj_matrix[i - 1, 2 * i] = 1
            adj_matrix[2 * i, i - 1] = 1  # Undirected edge

    return adj_matrix

def compute_eigen_properties(adj_matrix):
    # Compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(adj_matrix)

    # Sum of absolute eigenvalues (not altering original values)
    eigen_sum = np.sum(np.abs(eigenvalues))

    # Eigenvalue matrix (diagonal with signed eigenvalues)
    eigen_matrix = np.diag(eigenvalues)

    return eigenvalues, eigen_sum, eigen_matrix, eigenvectors

def main():
    print("\n=== Binary Tree Spectral Analysis Tool ===")
    try:
        n = int(input("Enter the number of nodes (e.g., 5 or 50): "))
        if n < 1:
            print("Please enter a positive integer.")
            return
    except ValueError:
        print("Invalid input. Please enter a valid integer.")
        return

    # Generate the adjacency matrix
    adj_matrix = generate_binary_tree_adjacency_matrix(n)

    # Compute eigenvalue-related properties
    eigenvalues, eigen_sum, eigen_matrix, eigenvectors = compute_eigen_properties(adj_matrix)

    # Display the outputs
    print("\nAdjacency Matrix:")
    print(adj_matrix)

    print("\nEigenvalues (original):")
    print(eigenvalues)

    print("\nSum of Absolute Eigenvalues:")
    print(eigen_sum)

    print("\nEigenvalue Matrix (Diagonal):")
    print(eigen_matrix)

    print("\nEigenvector Matrix (columns):")
    print(eigenvectors)

# ✅ Entry point
if __name__ == "__main__":
    main()



=== Binary Tree Spectral Analysis Tool ===


Enter the number of nodes (e.g., 5 or 50):  6



Adjacency Matrix:
[[0 1 1 0 0 0]
 [1 0 0 1 1 0]
 [1 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]

Eigenvalues (original):
[-1.90211303 -1.1755705  -0.          0.          1.1755705   1.90211303]

Sum of Absolute Eigenvalues:
6.155367074350506

Eigenvalue Matrix (Diagonal):
[[-1.90211303  0.          0.          0.          0.          0.        ]
 [ 0.         -1.1755705   0.          0.          0.          0.        ]
 [ 0.          0.         -0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.1755705   0.        ]
 [ 0.          0.          0.          0.          0.          1.90211303]]

Eigenvector Matrix (columns):
[[-0.51166727 -0.19543951  0.16302976  0.61108207  0.19543951  0.51166727]
 [ 0.60150096 -0.37174803 -0.         -0.         -0.37174803  0.60150096]
 [ 0.37174803  0.60150096 -0.         -0.          0.60150096  0.37174803]
 [-0.